hw01: first
murfel/java pull request #1
Opened 2017-09-16 22:59 UTC by murfel

2017-09-23 10:15 UTC, jzuken requested changes

2017-09-23 10:15 UTC, jzuken commented on hw01/src/name/murfel/hw01/MyHashMap.java
> +public class MyHashMap {
к классу тоже нужны доки

2017-09-23 10:15 UTC, jzuken commented on hw01/src/name/murfel/hw01/MyHashMap.java
> +public class MyHashMap {
в начале класса обычно размещают поля, а потом уже методы

2017-09-23 10:15 UTC, jzuken commented on hw01/src/name/murfel/hw01/MyHashMap.java
> +        if (list == null) return false;
такое лучше писать в две строки, читаемость кода выше становится

2017-09-23 10:15 UTC, jzuken commented on hw01/src/name/murfel/hw01/MyHashMap.java
> +     * Put an element with the key key and the value value into the hash map.
крутые доки

2017-09-23 10:15 UTC, jzuken commented on hw01/src/name/murfel/hw01/MyList.java
> +    public void add(String first, String second) {
а не лучше key и value?

2017-09-23 10:15 UTC, jzuken commented on hw01/src/name/murfel/hw01/MyHashMap.java
> +        for (int i = 0; i < list.size(); i++) {
не, это функциональность списка искать в себе элементы, хэш-таблице не нужно этим заниматься. оттого и эти уродливые массивы из двух элементов в интерфейсе

2017-09-24 10:10 UTC, murfel commented on hw01/src/name/murfel/hw01/MyHashMap.java
> +     * Put an element with the key key and the value value into the hash map.
В этом методе далее есть доки, и я считаю, что какая-то преамбула необходима, даже если она очевидная. Как вы думаете было бы лучше написать?

2017-09-24 17:44 UTC, jzuken commented on hw01/src/name/murfel/hw01/MyHashMap.java
> +     * Put an element with the key key and the value value into the hash map.
не, это был не сарказм. мне правда понравилось, как тут все джавадоки оформлены

2017-10-04 12:01 UTC, merged