Homework #08 Mock
murfel/java pull request #13
Opened 2017-11-29 11:00 UTC by murfel

2017-12-03 12:22 UTC, murfel commented on hw08_mock/src/test/java/CalculatorTest.java
> +        Stack<Integer> mockStack = mock(Stack.class);
На mock(Stack.class) идея пишет: Unchecked assignment. Причём запись mock(Stack<Integer>.class) не компилится. Я гуглила «how to pass parameterized class as argument», и нашла, что мне может помочь [super type token](http://gafter.blogspot.ru/2006/12/super-type-tokens.html), но я не поняла, как это использовать + есть сомнение, что это работает так же 2к17, как и в 2006 (год статьи по ссылке). Буду рада услышать, что бы вы посоветовали сделать.

2017-12-03 12:25 UTC, murfel commented on hw08_mock/src/test/java/CalculatorTest.java
> +//        Stack<Integer> mockStack = mock(Stack.class);
Без мока тест работает, но с моком тест падает с NPE. Как понять, в чём дело?

2017-12-03 12:34 UTC, murfel commented on hw08_mock/src/main/java/Calculator.java
> +        operation.put("+", (x, y) -> x + y);
Не понимаю, почему Идея выдаёт что-то вроде предупреждения сбоку (красный кружок с λ): Overrides method in BiFunction

2017-12-09 15:24 UTC, jzuken requested changes

2017-12-09 15:24 UTC, jzuken commented on hw08_mock/src/main/java/Stack.java
> +    private ArrayList<E> stack = new ArrayList<>();
ну так не интересно, по условию требовалось реализовать стек самостоятельно

2017-12-09 15:24 UTC, jzuken commented on hw08_mock/src/main/java/Stack.java
> +    private ArrayList<E> stack = new ArrayList<>();
и на стек тоже нужны тесты

2017-12-09 15:24 UTC, jzuken commented on hw08_mock/src/main/java/Calculator.java
> +        public Type type;
паблик поля в паблик классе? не надо лучше так делать

2017-12-09 15:24 UTC, jzuken commented on hw08_mock/src/test/java/CalculatorTest.java
> +import org.mockito.Mockito;
неиспользуемые импорты лучше убирать

2017-12-09 15:26 UTC, jzuken commented on hw08_mock/src/test/java/CalculatorTest.java
> +        Stack<Integer> mockStack = mock(Stack.class);
решения тут два -- либо писать SuppressWarnings("unchecked"), либо объявлять поле в тестовом классе с аннотацией Mock. в принципе, первый вариант тоже норм, т.к. тут мы явно знаем, что делаем

2017-12-09 15:30 UTC, jzuken commented on hw08_mock/src/test/java/CalculatorTest.java
> +//        Stack<Integer> mockStack = mock(Stack.class);
так же, как и всегда -- с помощью отладчика :)
вы вот ему сказали вызвать реализацию clear(), вот он её и вызывает. а поле stack то никто не создал, вот при попытке вызвать clear() у него всё и валится

2017-12-09 15:32 UTC, jzuken commented on hw08_mock/src/main/java/Calculator.java
> +        operation.put("+", (x, y) -> x + y);
ну потому что вы подали сюда лямбду, которая перекрывает метод apply() в BiFunction. это информационное сообщение, ничего плохого не случилось

2017-12-30 22:30 UTC, murfel commented on hw08_mock/src/test/java/CalculatorTest.java
> +//        Stack<Integer> mockStack = mock(Stack.class);
Поясните, почему «поле stack никто не создал»? Поле stack инициализируется при объявлении в 8 строке. Возможно, я неправильно понимаю, как работает мокито.

2017-12-31 10:50 UTC, jzuken commented on hw08_mock/src/test/java/CalculatorTest.java
> +//        Stack<Integer> mockStack = mock(Stack.class);
когда вы создаёте мок-объект для Stack, то оно создаёт просто пустую обёртку. никакие поля в классе Stack, включая поле stack, не инициализируется. и тогда когда вы вызываете фактическую реализацию clear(), она дёргала stack.clear(), который по сути был null'ом. отладчик -- полезная штука :)

2017-12-31 15:18 UTC, murfel commented on hw08_mock/hw08_mock.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Тест

2018-01-08 15:17 UTC, jzuken requested changes

2018-01-08 15:17 UTC, jzuken commented on hw08_mock/src/main/java/Stack.java
> +        return stack[--size];
это как-то совсем неаккуратно, а если до нуля дойдём? тут надо бы бросить исключение. и тест на него не забудьте
-1

2018-01-08 15:17 UTC, jzuken commented on hw08_mock/src/test/java/StackTest.java
> +    public void pushOne() throws Exception {
а оно правда что-то кидает? потому как если нет, то лучше не писать тут ничего

2018-02-03 15:36 UTC, merged